# Generated by Django 3.0.5 on 2020-04-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Molavi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raftar_mosbat',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
